version: '2.1'

services:

  app:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_TAG}.middlewares=narra"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${DCAPE_ROOT}/${LIB_PATH}:/var/lib/registry

